// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-67BXirxWaJaEBucOe8et-UJS64_upPo',
    appId: '1:609354382894:web:0ab893f333bc8a097929bf',
    messagingSenderId: '609354382894',
    projectId: 'riphahscd',
    authDomain: 'riphahscd.firebaseapp.com',
    storageBucket: 'riphahscd.firebasestorage.app',
    measurementId: 'G-EWQG7FVH5S',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBThfvYS9yyrjD-J1rMHLSISB_tzXooBE8',
    appId: '1:609354382894:ios:d544757e6ac360a97929bf',
    messagingSenderId: '609354382894',
    projectId: 'riphahscd',
    storageBucket: 'riphahscd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBThfvYS9yyrjD-J1rMHLSISB_tzXooBE8',
    appId: '1:609354382894:ios:d544757e6ac360a97929bf',
    messagingSenderId: '609354382894',
    projectId: 'riphahscd',
    storageBucket: 'riphahscd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-67BXirxWaJaEBucOe8et-UJS64_upPo',
    appId: '1:609354382894:web:9292f652506a01417929bf',
    messagingSenderId: '609354382894',
    projectId: 'riphahscd',
    authDomain: 'riphahscd.firebaseapp.com',
    storageBucket: 'riphahscd.firebasestorage.app',
    measurementId: 'G-BMLEVGPH4G',
  );
}
